name: wood_ring
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - albumentations=1.3.0
  - cudatoolkit=11.8
  - jupyter
  - matplotlib=3.7.1
  - numpy=1.24.3
  - opencv==4.8.0
  - pandas=1.5.3
  - pillow=9.5.0
  - pip==25.2
  - python=3.9.18
  - scikit-learn=1.2.2
  - tqdm
  - optuna
  - pyinstaller
prefix: E:\Test\wood_ring
